---
title: "quarto-gha-demo"
---

## Quarto

-   Credits: I started my journey based on 
    <https://jadeyryan.com/blog/2023-11-19_publish-quarto-website/>,
    but quickly looked elsewhere because the former blog post centers on Netlify
    as backend.

-   Instead of `usethis::use_git()`, I have at first committed the boilerplate
    Quarto project (as generated by the RStudio project wizard) locally and then
    pushed things to GitHub with:

```{r, eval=FALSE}
usethis::use_github()
```

-   The I followed instructions from <https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-01-basics.md>

-   In particular, I copied the [quarto-publish-example.yml](https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml)
    to `.github/workflows/quarto-publish.yml` in my repo.
    
-   As next step, I ran `quarto publish gh-pages` once as recommended.
    This sets up GH pages as needed.

Next, I learned to:

-   Customize the `quarto-publish-example.yml` workflow.

-   Track R package dependencies in a `DESCRIPTION` file, which can also be used
    outside the context of R *packages* ({usethis} is your friend).
